---

- name: Include server firewall to check
  include_vars: server.yml

- name: Obtain information about a powercat
  win_stat: 
    path: C:\Windows\system32\powercat.ps1
  register: file_info
      
- name: Copy powercat
  win_copy:
    src: powercat.ps1
    dest: C:\Windows\system32\powercat.ps1
  when: file_info|succeeded

- name: Put the listener up.
  win_shell: | 
     . powercat.ps1; powercat -t 600 -l -p {{ item.port }}
  when: item.server2 == ansible_hostname
  with_items: "{{ servers }}"
