---

- name: Fetching file
  fetch:
    src: /tmp/{{ ansible_hostname }}_output.csv
    dest: ./{{ ansible_hostname }}_output.csv
    flat: yes

- name: Execute Validation
  shell: ./validate.py linux
  args:
    executable: /bin/bash
  delegate_to: localhost
  run_once: true
