---

- name: Create linux inventory 1
  shell: printf "\tASDF\n" | awk -F',' '$1' linux.csv > temp0
  delegate_to: localhost
  run_once: true

- name: Create linux inventory 2
  shell: awk -F',' 'FNR > 1 { print  $1 " ansible_host="$4 }' temp0 > temp
  delegate_to: localhost
  run_once: true
  
- name: Create linux inventory - remove empty lines 3
  shell: awk NF temp > linux
  delegate_to: localhost
  run_once: true  
  
- name: Create linux2 inventory 1
  shell: printf "\tASDF\n" | awk -F',' '$2' linux.csv > temp00
  delegate_to: localhost
  run_once: true
  
- name: Create linux2 inventory 2
  shell: awk -F',' 'FNR > 1 { print  $2 " ansible_host="$8 }' temp00 > temp2
  delegate_to: localhost
  run_once: true

- name: Create linux2 inventory - remove empty lines 3
  shell: awk NF temp2 > temp3
  delegate_to: localhost
  run_once: true
 
- name: Create linux2 inventory 4
  shell: cat temp3 | uniq > linux2
  delegate_to: localhost
  run_once: true

- name: Create loop variables 1
  shell: chmod u+x create-loop.py
  delegate_to: localhost
  run_once: true
  
- name: Create loop variables 2
  shell: ./create-loop.py linux.csv
  delegate_to: localhost
  run_once: true

- name: Create loop variables 4
  shell: cp roles/validate-linux2/vars/server.yml roles/checkport-linux/vars/server.yml
  delegate_to: localhost
  run_once: true
  